"""Add password field.

Revision ID: 991398afce8f
Revises: 7febe70f67b8
Create Date: 2026-01-06 06:28:57.457703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991398afce8f'
down_revision = '7febe70f67b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
